FILE_EMOJIS = {
    ["window_utils.lua"] = "🪟🛠️",
    ["window_management.lua"] = "🪟️🚆",
    ["window_blacklist.lua"] = "🪟⬛",
    ["default_window_sizes.lua"] = "🪟🤔",
    ["log.lua"] = "📘",
    ["utils.lua"] = "🔧",
    ["boot.lua"] = "🚀",
    ["init.lua"] = "🔄",
    ["screen_color_and_brightness.lua"] = "🔆",
    ["morning_space.lua"] = "🌅",
    ["reset_apps.lua"] = "🔄",
    ["disconnect_from_wifi_when_on_ethernet.lua"] = "📶",
    ["caffeinate.lua"] = "☕",
    ["app_utils.lua"] = "📱",
    ["fresh_unlock.lua"] = "🔓",
    ["night_blocking.lua"] = "🌙",
    ["audio_devices.lua"] = "🎧"
}
